# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c963f32f863e971b817b01335c65e0d16040f36f6df1407dcb1c08a62f6d1cb38c1009d2fcf2f687b482baeee7ed9068d2e0b0a13789547b6000ba1990d5bdf4

test:
  secret_key_base: 0c8037cdbf561221da232309240781f4c41e7c7b30d1a77ee468376335aa74a4ef97e5e7b36df4204117f2d0b027719d88f6b2fc4115e5a85816309295c158de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
